version: '3'
services:
  web: 
    build: 
      context: .
      dockerfile: Docker.dev
    ports: 
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
  tests:
    build: 
      context: .
      dockerfile: Docker.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]
